DROP DATABASE IF EXISTS MiniWebShop;

create database MiniWebShop;
GO

USE MiniWebShop
GO

create table BRAND(
	ID int PRIMARY KEY IDENTITY(1,1),
	NAZIV VARCHAR(255)
);

create table NACIN_PLACANJA(
	ID tinyint PRIMARY KEY IDENTITY(1,1),
	NAZIV VARCHAR(50)
);

create table POPUST_KODOVI(
	ID int PRIMARY KEY IDENTITY(1,1),
	KOD VARCHAR(255),
	POPUST DECIMAL,
	ISKORISTEN bit
);

create table PROIZVOD(
	ID int PRIMARY KEY IDENTITY(1,1),
	NAZIV VARCHAR(255),
	OPIS VARCHAR(255),
	CIJENA DECIMAL,
	KOLICINA NUMERIC,
	BRAND_ID int NOT NULL

	CONSTRAINT fkey_BRAND_ID FOREIGN KEY (BRAND_ID)
        REFERENCES BRAND (ID)
        ON DELETE CASCADE
);

create table NARUDZBA(
	ID int PRIMARY KEY IDENTITY(1,1),
	DATUM DATETIME,
	UKUPNA_CIJENA_BEZ_P MONEY,
	UKUPNA_CIJENA_S_P MONEY,
	KOD_ZA_POPUST_ID int,
	NACIN_PLACANJA_ID tinyint,
	BROJ_KARTICE VARCHAR(20),
	EMAIL VARCHAR(255),
	BROJ_MOBITELA VARCHAR(13),
	ADRESA_DOSTAVE VARCHAR(255),
	NAPOMENA VARCHAR(255)

	CONSTRAINT fkey_KOD_ZA_POPUST_ID FOREIGN KEY (KOD_ZA_POPUST_ID)
		REFERENCES POPUST_KODOVI (ID)
		ON DELETE SET NULL,
	CONSTRAINT fkey_NACIN_PLACANJA_ID FOREIGN KEY (NACIN_PLACANJA_ID)
		REFERENCES NACIN_PLACANJA (ID)
		ON DELETE SET NULL
);

create table NARUDZBA_PROIZVODI(
	ID int PRIMARY KEY IDENTITY(1,1),
	NARUDZBA_ID int NOT NULL,
	PROIZVOD_ID int

	CONSTRAINT fkey_NARUDZBA_ID FOREIGN KEY (NARUDZBA_ID)
		REFERENCES NARUDZBA (ID)
		ON DELETE CASCADE,
	CONSTRAINT fkey_PROIZVOD_ID FOREIGN KEY (PROIZVOD_ID)
		REFERENCES PROIZVOD (ID)
		ON DELETE SET NULL
);

/*Kreiranje testnih podataka za NACIN_PLACANJA*/
INSERT INTO NACIN_PLACANJA (NAZIV) VALUES ('KARTIČNO');
INSERT INTO NACIN_PLACANJA (NAZIV) VALUES ('GOTOVINSKO');

/*Kreiranje testnih podataka za POPUST_KODOVI*/
DECLARE @counter int
SET @counter = 0
WHILE @counter < 10
Begin
	INSERT INTO POPUST_KODOVI (	KOD, POPUST, ISKORISTEN )
		VALUES (
			SUBSTRING(CONVERT(varchar(40), NEWID()),0,9),
			RAND()*(99)+0.1,
			0
		)
	SET @counter = @counter + 1;
END

/*Kreiranje testnih podataka za BRAND*/
INSERT INTO BRAND (NAZIV) VALUES ('RAZER');
INSERT INTO BRAND (NAZIV) VALUES ('KINGSTON');
INSERT INTO BRAND (NAZIV) VALUES ('MANTA');
INSERT INTO BRAND (NAZIV) VALUES ('Sony');

/*Kreiranje testnih podataka za PROIZVOD*/
INSERT INTO PROIZVOD (NAZIV, OPIS, CIJENA, KOLICINA, BRAND_ID) VALUES ('Miš RAZER DEATHADDER', 'Bežični miš', 150.5, 10, 1);
INSERT INTO PROIZVOD (NAZIV, OPIS, CIJENA, KOLICINA, BRAND_ID) VALUES ('Mikrofon KINGSTON HyperX QuadCast S ', 'Stolni mikrofon', 1099, 15, 2);
INSERT INTO PROIZVOD (NAZIV, OPIS, CIJENA, KOLICINA, BRAND_ID) VALUES ('SSD 1000 GB KINGSTON NV1', 'M.2/NVMe flash memorija', 730.55, 20, 2);
INSERT INTO PROIZVOD (NAZIV, OPIS, CIJENA, KOLICINA, BRAND_ID) VALUES ('Karaoke MANTA SPK5210', 'Zvučnik + mikrofon', 799, 10, 3);
INSERT INTO PROIZVOD (NAZIV, OPIS, CIJENA, KOLICINA, BRAND_ID) VALUES ('Slušalice SONY WFC500B.CE7 ', 'Bežične slušalice ', 589, 100, 4);

/*Kreiranje testnih podataka za NARUDZBA*/
INSERT INTO NARUDZBA (DATUM, UKUPNA_CIJENA_BEZ_P, UKUPNA_CIJENA_S_P, KOD_ZA_POPUST_ID, NACIN_PLACANJA_ID, BROJ_KARTICE, EMAIL, BROJ_MOBITELA, ADRESA_DOSTAVE, NAPOMENA) 
	VALUES (
		'20201018 10:34:09',
		1500,
		1350,
		1,
		1,
		'1234 4444 5858 7458',
		'nema@nema.hr',
		'+385981231234',
		'Trg Bana Jelačića 1, 10000 Zagreb',
		'Nema napomene'
	);
INSERT INTO NARUDZBA (DATUM, UKUPNA_CIJENA_BEZ_P, UKUPNA_CIJENA_S_P, KOD_ZA_POPUST_ID, NACIN_PLACANJA_ID, BROJ_KARTICE, EMAIL, BROJ_MOBITELA, ADRESA_DOSTAVE, NAPOMENA) 
	VALUES (
		'20210122 13:22:45',
		200,
		170,
		2,
		1,
		'4321 3333 7474 9658',
		'pero.peric@king-ict.hr',
		'+385910009876',
		'Vinogradska 20a, 44000 Sisak',
		'Molim HITNO isporučite našu robu'
	);
INSERT INTO NARUDZBA (DATUM, UKUPNA_CIJENA_BEZ_P, UKUPNA_CIJENA_S_P, KOD_ZA_POPUST_ID, NACIN_PLACANJA_ID, BROJ_KARTICE, EMAIL, BROJ_MOBITELA, ADRESA_DOSTAVE, NAPOMENA) 
	VALUES (
		'20220510 05:15:20',
		650,
		539,
		3,
		2,
		'5825 2222 7474 1245',
		'dinko.dinkic@gmail.ba',
		'+385957438562',
		'Vukovarska 45, 31000 Osijek',
		'Drugi kat'
	);

/*Kreiranje testnih podataka za NARUDZBA_PROIZVOD*/
INSERT INTO NARUDZBA_PROIZVODI (NARUDZBA_ID, PROIZVOD_ID) VALUES (1, 2);
INSERT INTO NARUDZBA_PROIZVODI (NARUDZBA_ID, PROIZVOD_ID) VALUES (1, 5);
INSERT INTO NARUDZBA_PROIZVODI (NARUDZBA_ID, PROIZVOD_ID) VALUES (2, 1);
INSERT INTO NARUDZBA_PROIZVODI (NARUDZBA_ID, PROIZVOD_ID) VALUES (3, 3);





